# Generated by Django 3.1.7 on 2021-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210227_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '임시저장'), (1, '글 게시')], default=0, verbose_name='게시상태'),
        ),
    ]
