# Generated by Django 3.1.7 on 2021-02-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
